version: '3'

# Services
services:
  # Apache + PHP
  apache_php_composer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'apache_php_composer-server'
    volumes:
      - ./.docker/apache/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache/httpd.conf:/etc/apache2/conf-available/httpd.conf
      - ./.docker/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src/:/var/www/html
    expose:
      - 80
    ports:
      - '8082:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql
    networks:
      - tinder
  mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: tinder
      MARIADB_USER: pringao
      MARIADB_PASSWORD: passwordpringao
    volumes:
      - ./.mariadb:/var/lib/mysql:Z
    networks:
      - tinder
    ports:
      - '3307:3306'
  phpmyadmin:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: pringao
      MYSQL_PASSWORD: passwordpringao
      PMA_HOST: mysql
    ports:
      - '8083:80'
    links:
      - mysql
    networks:
      - tinder
networks:
  tinder:
    name: tinder
    driver: bridge

    ##Descomentar si se desea acceder con una aplicación de escritorio
    #ports:
      #- '3306:3306'
# Lanzar con
# docker-compose up -d –build

# Ver los logs con
# docker-compose logs -f

# Bash: docker-compose exec apache_php_composer bash

# https://www.bornfight.com/blog/blog-lamp-docker-setup-with-php-8-and-mariadb-for-symfony-projects/

# https://www.cloudsavvyit.com/10528/how-to-use-docker-to-containerise-php-and-apache/
